# PyMBE environment image
image: registry.gitlab.com/jgreiner/pymbe/pymbe_env:latest

stages:
  - Type Checking
  - Testing

mypy:
  stage: Type Checking
  needs: []
  script:
    - mypy --ignore-missing-imports --warn-redundant-casts pymbe

pytest:
  stage: Testing
  needs: []
  script:
    - echo "MBECCLIB = '${MBECC_DIR}/libmbecc.so'" > pymbe/settings.py
    - python3 -m pytest --junitxml=../report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
