# PyMBE environment image
image: registry.gitlab.com/jgreiner/pymbe/pymbe_env_image:latest

stages:
  - Static Analysis
  - Type Checking
  - Test

#pylint:
#  stage: Static Analysis
#  script:
#    - pip install pylint
#    - pylint -d C0301 src/*.py

mypy:
  stage: Type Checking
  script:
    - mypy --ignore-missing-imports src

pytest:
  stage: Test
  script:
    - cd src && python3 -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml
