# Language image
image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

# Pip's cache doesn't store the python packages
# Install packages in a virtualenv and cache it as well.
cache:
  paths:
    - .cache/pip
    - .venv/

before_script:
  - python -V  # Print out python version for debugging
  - pip install virtualenv
  - virtualenv .venv
  - source .venv/bin/activate
  - pip install mpi4py
  - pip install pyscf
  - pip install seaborn
  - pip install pytest

stages:
  - Static Analysis
  - Type Checking
  - Test

#pylint:
#  stage: Static Analysis
#  script:
#    - pip install pylint
#    - pylint -d C0301 src/*.py

mypy:
  stage: Type Checking
  script:
    - pip install mypy
    - mypy src/*.py

pytest:
  stage: Test
  script:
    - pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml