# PyMBE environment image
image: registry.gitlab.com/jgreiner/pymbe/pymbe_env_image:latest

stages:
  - Type Checking
  - Testing

mypy:
  stage: Type Checking
  needs: []
  script:
    - mypy --ignore-missing-imports --warn-redundant-casts pymbe

pytest:
  stage: Testing
  needs: []
  script:
    - echo "MBECCLIB = '${MBECC_DIR}/libmbecc.so'" > pymbe/settings.py
    - python3 -m pytest -x --junitxml=../report.xml pymbe/tests/system_tests/test_system.py::test_system[h2o-fci-genfock-can-vac]
  artifacts:
    when: always
    reports:
      junit: report.xml
